import type { LongevityReport } from '@/store/onboardingStore';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Alert } from 'react-native';

const GREEN = '#09E27D';
const BLACK = '#000000';
const GRAY = '#555555';
const DIVIDER = '#E0E0E0';

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function section(title: string, body: string) {
  return `<div class="section"><h2>${esc(title)}</h2>${body}</div>`;
}

function sub(title: string, body: string) {
  return `<h3>${esc(title)}</h3><p>${esc(body)}</p>`;
}

function para(text: string) {
  return text ? `<p>${esc(text)}</p>` : '';
}

function buildHtml(report: LongevityReport, firstName?: string): string {
  const titleName = firstName ? `${firstName}'s` : 'Your';
  const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

  // ── helpers to safely pull nested data ──────────────────────────────────────
  const j = report.your_journey as any;
  const journeyIntro: string = j?.intro ?? '';
  const milestones: any[] = Array.isArray(j?.milestones) ? j.milestones : [];

  const cf = report.critical_findings as any;
  const critIntro: string = cf?.intro ?? '';
  const critItems: any[] = Array.isArray(cf?.items) ? cf.items : [];

  const pf = report.positive_findings as any;
  const posIntro: string = pf?.intro ?? '';
  const posItems: any[] = Array.isArray(pf?.items) ? pf.items : [];

  const dt = report.doctor_topics as any;
  const docIntro: string = dt?.intro ?? '';
  const docItems: any[] = Array.isArray(dt?.items) ? dt.items : [];

  const rm = report.roadmap as any;
  const roadIntro: string = rm?.intro ?? '';
  const roadSteps: any[] = Array.isArray(rm?.steps) ? rm.steps : [];

  const bg = report.behavioral_goals as any;
  const behavIntro: string = bg?.intro ?? '';
  const behavItems: any[] = Array.isArray(bg?.items) ? bg.items : [];

  const di = report.diet as any;
  const dietIntro: string = di?.intro ?? '';
  const dietItems: any[] = Array.isArray(di?.items) ? di.items : [];

  const sp = report.supplements as any;
  const suppIntro: string = sp?.intro ?? '';
  const suppItems: any[] = Array.isArray(sp?.items) ? sp.items : [];

  const dv = report.devices as any;
  const devIntro: string = dv?.intro ?? '';
  const devItems: any[] = Array.isArray(dv?.items) ? dv.items : [];

  const sc = report.screenings as any;
  const scrIntro: string = sc?.intro ?? '';
  const scrItems: any[] = Array.isArray(sc?.items) ? sc.items : [];

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, Helvetica Neue, Arial, sans-serif;
    color: ${BLACK};
    background: #fff;
    padding: 52px 56px;
    font-size: 13px;
    line-height: 1.7;
  }
  .report-title {
    font-size: 32px;
    font-weight: 400;
    letter-spacing: -0.5px;
    line-height: 1.15;
    color: ${BLACK};
  }
  .report-date {
    font-size: 12px;
    color: ${GRAY};
    margin-top: 8px;
  }
  .divider {
    height: 2px;
    background: ${GREEN};
    border-radius: 1px;
    margin: 16px 0 22px;
  }
  .notice {
    font-size: 11.5px;
    color: ${GRAY};
    border-left: 3px solid ${GREEN};
    padding-left: 12px;
    margin-bottom: 30px;
    line-height: 1.65;
  }
  .section { margin-bottom: 26px; }
  h2 {
    font-size: 18px;
    font-weight: 700;
    color: ${BLACK};
    margin-bottom: 10px;
    border-top: 1px solid ${DIVIDER};
    padding-top: 18px;
    letter-spacing: -0.2px;
  }
  h3 {
    font-size: 13.5px;
    font-weight: 700;
    color: ${BLACK};
    margin-top: 14px;
    margin-bottom: 4px;
  }
  p {
    font-size: 13px;
    color: ${GRAY};
    margin-bottom: 6px;
    line-height: 1.75;
  }
  .footer {
    margin-top: 44px;
    padding-top: 16px;
    border-top: 1px solid ${DIVIDER};
    font-size: 10.5px;
    color: #999;
    line-height: 1.65;
  }
</style>
</head>
<body>

<div class="report-title">${esc(titleName)}<br/>Longevity Report</div>
<div class="report-date">Created in The Life Lab &nbsp;·&nbsp; Last updated ${dateStr}</div>
<div class="divider"></div>

<div class="notice">
  This report was generated by an AI trained in accordance with a clinical framework developed by our Clinical Board.
  Our board comprises a multidisciplinary team of medical experts, including oncologists, endocrinologists, and other specialists.
  For more information regarding our clinical standards and board members, please visit <strong>deathclock.co/about</strong>
</div>

${section('Your Journey', `
  ${para(journeyIntro)}
  ${milestones.map(m => sub(m.title ?? '', m.body ?? '')).join('')}
`)}

${section('Progress and Trends', para(report.progress_and_trends))}

${section('Critical Findings', `
  ${para(critIntro)}
  ${critItems.map(i => sub(i.title ?? '', i.body ?? '')).join('')}
`)}

${section('Positive Findings', `
  ${para(posIntro)}
  ${posItems.map(i => sub(i.title ?? '', `${i.body ?? ''}${i.next_step ? `\nNext Step: ${i.next_step}` : ''}`)).join('')}
`)}

${section('Biomarker Goals', `<p>We can't set specific biomarker goals until you complete your first blood test. Once your results are in, this section will populate with your personalized targets.</p>`)}

${section('Topics to Discuss with Your Doctor', `
  ${para(docIntro)}
  ${docItems.map(i => sub(i.title ?? '', `${i.body ?? ''}${i.goal ? `\nGoal: ${i.goal}` : ''}`)).join('')}
`)}

${section('Hormone Analysis', para(report.hormone_analysis))}

${section('Genetics', para(report.genetics))}

${section('What to Do Next — Your Roadmap', `
  ${para(roadIntro)}
  ${roadSteps.map(s => sub(s.title ?? '', s.body ?? '')).join('')}
`)}

${section('Behavioral Goals', `
  ${para(behavIntro)}
  ${behavItems.map(i => sub(i.title ?? '', `${i.body ?? ''}${i.frequency ? `\nFrequency: ${i.frequency}` : ''}`)).join('')}
`)}

${section('Diet', `
  ${para(dietIntro)}
  ${dietItems.map(i => sub(i.title ?? '', `${i.body ?? ''}${i.how ? `\nHow to Start: ${i.how}` : ''}`)).join('')}
`)}

${section('Supplements', `
  ${para(suppIntro)}
  ${suppItems.map(i => sub(i.title ?? '', i.body ?? '')).join('')}
`)}

${section('Devices & Equipment', `
  ${para(devIntro)}
  ${devItems.map(i => sub(i.title ?? '', i.body ?? '')).join('')}
`)}

${section('Prescriptions', para(report.prescriptions))}

${section('Screenings', `
  ${para(scrIntro)}
  ${scrItems.map(i => sub(i.title ?? '', i.body ?? '')).join('')}
`)}

<div class="footer">
  This report is for informational purposes only and does not constitute medical advice, diagnosis, or treatment.
  Always seek the advice of your physician or other qualified health provider with any questions you may have
  regarding a medical condition or health objectives.
</div>

</body>
</html>`;
}

export async function generateAndShareReport(report?: LongevityReport | null, firstName?: string) {
  try {
    const html = report ? buildHtml(report, firstName) : buildFallbackHtml();
    const { uri } = await Print.printToFileAsync({ html, base64: false });

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: firstName ? `${firstName}'s Longevity Report` : 'Longevity Report',
        UTI: 'com.adobe.pdf',
      });
    } else {
      Alert.alert('Sharing not available', 'PDF was generated but sharing is not supported on this device.');
    }
  } catch (e) {
    Alert.alert('Error', 'Could not generate the PDF. Please try again.');
    console.error(e);
  }
}

function buildFallbackHtml(): string {
  const dateStr = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  return `<!DOCTYPE html><html><body style="font-family:sans-serif;padding:52px 56px;">
    <div style="font-size:32px;font-weight:400;">Your Longevity Report</div>
    <div style="font-size:12px;color:#555;margin-top:8px;">Last updated ${dateStr}</div>
    <hr style="border:none;border-top:2px solid #09E27D;margin:16px 0 22px;" />
    <p style="color:#555;">Your report is still being generated. Please open the app and wait for the report to finish loading, then try exporting again.</p>
  </body></html>`;
}
